fix add_compile_options
  /usr/xcc/armv7-unknown-linux-gnueabi/bin/armv7-unknown-linux-gnueabi-g++ --sysroot=/usr/xcc/armv7-unknown-linux-gnueabi/armv7-unknown-linux-gnueabi/sysroot  -D_vosk_EXPORTS -I/io/src -I/opt/kaldi/src -I/opt/kaldi/tools/openfst/include  -I /usr/xcc/armv7-unknown-linux-gnueabi/include/ -O3 -DNDEBUG -fPIC   "-I/opt/python/cp37-cp37m/include/python3.7m -I/opt/python/cp37-cp37m/include/python3.7m  -Wno-unused-result -Wsign-compare -I/usr/xcc/armv7-unknown-linux-gnueabi/include -DNDEBUG -g -fwrapv -O3 -Wall" -std=c++11 -O3 -DFST_NO_DYNAMIC_LINKING -o CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o -c /tmp/pip-req-build-e69_n4de/build/temp.linux-armv7l-3.7/voskPYTHON_wrap.cxx
  /tmp/pip-req-build-e69_n4de/build/temp.linux-armv7l-3.7/voskPYTHON_wrap.cxx:178:21: fatal error: Python.h: No such file or directory
   # include <Python.h>